#!/usr/bin/env python3
number = input("Please enter a number: ")
number = int(number)
if number == 0:
    print("This number is equal to zero.")
else:
    print("Thiis number is Different from zero.")
